name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  workflow_call:
    secrets:
      DEV_API_KEY:
        required: true
      DEV_CLIENT_ID:
        required: true
      DEV_CLIENT_SECRET:
        required: true

defaults:
  run:
    working-directory: .
jobs:
  test:
    name: Running the Python test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
      - name: Run
        env:
          API_KEY: ${{ secrets.DEV_API_KEY }}
          CLIENT_ID: ${{ secrets.DEV_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEV_CLIENT_SECRET }}
          API_HOST: https://api.lfmdev.in
          AUTH_HOST: https://auth.lfmdev.in
          BRAND_ID: 6650
        run: |
          python3 setup.py pytest
