name: release
on:
  push:
    tags:
      - v*
defaults:
  run:
    working-directory: .
jobs:
  test:
    name: Running the Python test suite
    uses: ./.github/workflows/ci.yml

  upload-test-pypi:
    name: Uploading to PyPI
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build twine setuptools wheel
      - name: Build distribution
        run: python3 -m build
      - name: Upload
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: python3 -m twine upload dist/*
