name: Code Scans

on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  rapid-detect:
    name: Rapid Scan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event.schedule != '0 5 * * *'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install project dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          python setup.py install
          pip install -r requirements.txt
      - name: Run Synopsys Detect (Rapid Mode)
        uses: synopsys-sig/detect-action@v0.3.0
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
          DETECT_PROJECT_VERSION_PHRASE: DEVELOPMENT
          DETECT_PROJECT_VERSION_UPDATE: true
          DETECT_DETECTOR_SEARCH_DEPTH: 1
          DETECT_PIP_REQUIREMENTS_PATH: requirements.txt
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.14.0
          scan-mode: RAPID
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}

  intelligent-detect:
    name: Intelligent Scan
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 5 * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install project dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          python setup.py install
          pip install -r requirements.txt
      - name: Run Synopsys Detect (Intelligent Mode)
        uses: synopsys-sig/detect-action@v0.3.0
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
          DETECT_PROJECT_VERSION_PHRASE: DEVELOPMENT
          DETECT_PROJECT_VERSION_UPDATE: true
          DETECT_DETECTOR_SEARCH_DEPTH: 1
          DETECT_PIP_REQUIREMENTS_PATH: requirements.txt
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.14.0
          scan-mode: INTELLIGENT
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}

  release-detect:
    name: Production Intelligent Scan
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'v')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install project dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          python setup.py install
          pip install -r requirements.txt
      - name: Set variables for scan
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Run Synopsys Detect (Intelligent Mode)
        uses: synopsys-sig/detect-action@v0.3.0
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}-${{steps.vars.outputs.sha_short}}
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}-${{steps.vars.outputs.sha_short}}
          DETECT_PROJECT_VERSION_PHRASE: RELEASED
          DETECT_PROJECT_VERSION_UPDATE: true
          DETECT_DETECTOR_SEARCH_DEPTH: 1
          DETECT_PIP_REQUIREMENTS_PATH: requirements.txt
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.14.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
