name: test-release
on:
  push:
    tags:
      - v*
defaults:
  run:
    working-directory: python
jobs:
  test:
    name: Running the Python test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest pytest-recording
      - name: Run
        run: |
          #pytest --record-mode=once tests/

  upload-test-pypi:
    name: Uploading to Test PyPI
    runs-on: ubuntu-latest
    #needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build twine setuptools wheel
      - name: Build distribution
        run: python3 -m build
      - name: Upload
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: python3 -m twine upload -r testpypi dist/*
